[package]
name = "malleable-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
indexmap = { version = "2.7.0", features = ["serde"] }
log = "0.4.22"
env_logger = "0.11.5"
ring = "0.17.8"
regex = "1.11.1"
anyhow = "1.0.94"
rand = "0.8.5"
rot13 = "0.1.1"
base64 = "0.22.1"
image = "0.21"
cryptify = "3.1.1"
ftail = "0.1.2"
flate2 = "1.0.35"
collected_data = { path = "../collected_data" }
bincode = "1"
decryptor = { path = "../crypto/decryptor" }
